name: FinMind
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.6.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - certifi=2024.6.2
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - greenlet=3.0.3
  - idna=3.7
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libsqlite=3.45.3
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - loguru=0.7.2
  - ncurses=6.4.20240210
  - numpy=1.26.4
  - openssl=3.3.1
  - pandas=2.2.2
  - pip=24.0
  - pydantic=2.7.1
  - pydantic-core=2.18.2
  - pymysql=1.1.0
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytz=2024.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=69.5.1
  - six=1.16.0
  - sqlalchemy=2.0.30
  - tk=8.6.13
  - tqdm=4.62.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - .
