# version line obsolete in newer docker-compose version
# version: '3'
services:
  mysql:
      image: mysql:8.4
    # 設定 mysql 使用原生認證的密碼 hash
    # command: mysqld --default-authentication-plugin=mysql_native_password
    # 更新到8.4版適用寫法
      command: ["mysqld", "--mysql-native-password=ON"]
      ports:
          # docker publish port 3306 to 3306
          # (將 docker 內部 ip 3306, 跟外部 3306 做連結)
          - 3306:3306
      # - target: 3306
      #   published: 3306
      #   mode: host
      environment: # 環境變數, 設置 db, user, password, root_password
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
      volumes:
          - mysql:/var/lib/mysql
          # share volumes of docker container to outside volume,
          # let data persist
          # 將 docker container 的 volumes 跟外部 volumes 做連結,
          # 讓資料不會因為, container close or update, 而遺失
      # swarm 設定
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.labels.mysql == true]
      networks:
          - my_network

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.2.0
      links: 
          - mysql:db
      ports:
          - 8080:80
      environment: # swarm架構需額外指定MYSQL host位置，這裡用service名指定
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
          PMA_HOST: mysql
      depends_on:
        - mysql
      # swarm 設定
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.labels.mysql == true]
      networks:
          - my_network
     
networks:
  my_network:
    # 加入已經存在的網路
    external: true

volumes:
  mysql:
    external: true